stages:
  - build    # 线上代码打包
  - deploy   # 部署到开发环境，同步到 SVN


前端代码打包:
  stage: build
  artifacts:
    expire_in: 20 min
    paths:
      - dist/
  script:
    - nvm use
    - PROJECT_DEPS_DIR=~/${CI_PROJECT_PATH//\//_}_deps
    - mkdir -p $PROJECT_DEPS_DIR
    - ln -sf $(pwd)/package*.json $PROJECT_DEPS_DIR/
    - npm install --registry=https://registry.npm.taobao.org --prefix=$PROJECT_DEPS_DIR
    - NODE_PATH=$PROJECT_DEPS_DIR/node_modules
    - ln -sf $NODE_PATH node_modules
    - npm run build
    - unset NODE_PATH PROJECT_DEPS_DIR
  only:  # 上线分支自动打包
    - /^(release|hotfix)\/.+$/


# 同步代码到svn：仅支持release|hotfix分支
同步代码到SVN:
  stage: deploy
  script:
    - git2svn -m "dist/*:/tob/web/sales" --alias "数说h5" --sendmail --notify
  only:
    - /^(release|hotfix)\/.+$/

# 自动创建 Tag
创建Tag:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - autotag
  only:
    - master